export const medicalGuidelineTopics = [
    { 
        label: "ANTIMICROBIAL TREATMENT AND PROPHYLAXIS GUIDELINES", 
        flag: "🦠", 
        subtopics: [
            "GENERAL GUIDELINES",
            "PRINCIPLES OF ANTIMICROBIAL USE",
            "NOTES ON SPECIFIC ANTIMICROBIALS",
            "PYREXIA/FEVER OF UNKNOWN ORIGIN GENERAL RECOMMENDATIONS"
        ]
    },
    { 
        label: "BASIC INFECTION PREVENTION AND CONTROL MEASURES", 
        flag: "🧴",
        subtopics: [
            "GENERAL NOTES",
            "CATEGORIES OF INFECTION CONTROL",
            "PRACTICES STANDARD PRECAUTIONS",
            "TRANSMISSION-BASED PRECAUTIONS"
        ]
    },
    { 
        label: "SEVERE ACUTE RESPIRATORY SYNDROME CORONAVIRUS-2: COVID-19", 
        flag: "🦠",
        subtopics: [
            "GENERAL NOTE",
            "TESTING FOR COVID",
            "INFECTION PREVENTION AND CONTROL",
            "HANDLING OF CONTACTS OF COVID",
            "MANAGING A CASE",
            "POST DISCHARGE",
            "RECOMMENDED ANTIVIRAL INTERVENTION",
        ]
    },
    { 
        label: "PAEDIATRIC CONDITIONS", 
        flag: "🧒",
        subtopics: [
            "NEONATAL CONDITIONS",
            "ROUTINE MANAGEMENT AT BIRTH",
            "RESUSCITATION OF THE NEWBORN FEEDING AND FLUIDS",
            "NEONATAL INFECTIONS",
            "JAUNDICE",
            "CONVULSIONS",
            "RESPIRATORY DISTRESS SYNDROME (RDS)",
            "VITAMINS AND IRON PAEDIATRIC CONDITIONS",
            "GENERAL GUIDELINES ON THE USE OF ANTIBIOTICS",
            "ACUTE RESPIRATORY INFECTIONS DIARRHOEA IN CHILDREN",
            "ACUTE MALNUTRITION",
        ]
    },
    { 
        label: "PAEDIATRIC HIV CONDITIONS", 
        flag: "🧒🌍",
        subtopics: [
           
            "GENERAL NOTES ",
"MANAGEMENT OF SPECIFIC HIV RELATED CONDITIONS ",
"PAEDIATRIC MEDICINES DOSES",
        ]
    },
    { 
        label: "IMMUNISATION", 
        flag: "💉",
        subtopics: [
            "GENERAL NOTES",
            "IMMUNISATION SCHEDULE FOR CHILDREN", 
            "IMMUNISATION DETAILS FOR AVAILABLE VACCINES",

        ]
    },
    { 
        label: "OBSTETRIC AND GYNAECOLOGICAL CONDITIONS", 
        flag: "🤰",
        subtopics: [
            "GENERAL NOTES",
"HORMONAL CONTRACEPTION",
"ORAL CONTRACEPTIVES",
"MEDICINES INTERACTIONS WITH ORAL CONTRACEPTIVES",
"LONG TERM HORMONAL CONTRACEPTIVES", 
"ANAESTHESIA, ANALGESIA, ANTACIDS",
"CERVICAL RIPENERS/ LABOUR",
"TERMINATION OF PREGNANCY",
"INFECTIONS, GENITO-URINARY TRACT DURING PREGNANCY PRE-LABOUR RUPTURE OF MEMBRANES",
"PROPHYLAXIS FOR CAESAREAN SECTION",
"NAUSEA AND VOMITING NI PREGNANCY",
"ANAEMIA DURING PREGNANCY", 
"CARDIAC DISEASE NI PREGNANCY", 
"HYPERTENSION DISEASE NI PREGANCY ",
"DIABETES IN PREGNANCY",
"MEDICINES IN PREGNANCY AND LACTATION",
        ]
    },
    { 
        label: "SEXUALLY TRANSMITTED INFECTIONS (STIs)", 
        flag: "🦠",
        subtopics: [
            "GENERAL NOTES",
"URETHRAL DISCHARGE NI MEN",
"VAGINAL DISCHARGE NI WOMEN",
"ANAL AND RECTAL INFECTIONS",
"GENITAL ULCERSNI MEN &WOMEN (+/-BUBOES)",
"GRANULATING ULCERS WITHOUT BUBOES", 
"BUBOES WITHOUT ULCE",
"ACUTE EPIDIDYMO-ORCHITIS", 
"SYPHILIS", 
"GENITAL WARTS (CONDYLOMATA ACUMINATE)",
"MOLLUSCUM CONTAGIOSUM ",
"PEDICULOSIS PUBIS (PUBIC LICE)",
"OPHTHALMIA NEONATORUM",
        ]
    },
    { 
        label: "HIV RELATED DISEASES", 
        flag: "🌍",
        subtopics: [
            "GENERAL GUIDELINES",
 "CLINICAL PRESENTATION",
 "GENERAL NOTES",
 "COTRIMOXAZOLE PROPHYLAXIS:",
"PERSISTENT GENERALISED LYMPHADENOPATHY",
 "ORAL AND OESOPHAGEAL CANDIDIASIS (THRUSH)", 
"DIARRHOEA - ACUTE",
 "DIARRHOEA - CHRONIC",
 "WASTING SYNDROME (SLIM DISEASE)", 
 "RESPIRATORY CONDITIONS", 
"HEADACHE &PROBLEMS OF THE NERVOUS SYSTEM ",
"HEADACHE AND MENINGITIS",
 "AIDS DEMENTIA COMPLEX",
 "HIV RELATED SKIN CONDITIONS",
"HERPES ZOSTER (SHINGLES)",
"POST-HERPETIC NEURALGIA",
"FOLLICULITIS",
"HERPES SIMPLEX",
"SEBORRHEIC DERMATITIS",
"PRURIGO OR PAPULAR PRURITIC DERMATOSES MEDICINE REACTIONS",
"KAPOSI'S SARCOMA",
        ]
    },
    { 
        label: "ANTIRETROVIRAL THERAPY (ART)", 
        flag: "💊",
        subtopics: [
           "GOALS FOR ART",
"CRITERIA FOR ART NI ADOLESCENCE AND ADULTS",
"RECOMMENDED TREATMENT REGIMENS FOR ADOLESCENTS AND ADULTS", 
"SUBSTITUTION NI THE EVENT OF MEDICINE TOXICITY / ADVERSE EVENTS AND UNAVAILABILITY",
"USE OF ARVS NI PATIENTS WITH TB",
"PATIENTS WTIH TB WHO ARE NOT YET ON ART",
"PATIENTS WHO DEVELOP TB WHEN ALREADY ON ART",
"USE OF ARVS IN PATIENTS WITH CRYPTOCOCCAL MENINGITIS PRE-EXPOSURE PROPHYLAXIS (PREP)",
        ]
    },
    { 
        label: "USE OF ARVs FOR PMTCT", 
        flag: "🤰🌍",
        subtopics: [
            "GENERAL NOTES",
"INFANT AND YOUNG CHILD FEEDING RECOMMENDATIONS",
"ARV PROPHYLAXIS NI AN HIV-EXPOSED INFANT",
            
        ]
    },
    { 
        label: "TUBERCULOSIS (TB)", 
        flag: "🧬",
        subtopics: [
            "PREVENTION",
            "PRIMARY PREVENTION",
            "SECONDARY PREVENTION",
            "CASE MANAGE",
            "MEDICINE REGIMENS FOR TUBERCULOSIS",
            "CATEGORY I",
            "CATEGORY I",
            "DAILY DOSES BY WEIGHT - CATEGORY I", 
            "DAILY DOSES BY WEIGHT - CATEGORY I",
        ]
    },
    { 
        label: "TROPICAL DISEASES", 
        flag: "🦟",
        subtopics: [
            "ANTHRAX (CUTANEOUS)", 
            "TICK TYPHUS (AFRICAN)", 
            "RABIES",
            "BILHARZIA (SCHISTOSOMA MANSONI &HAEMATOBIUM) HELMINTHIASIS",
            "PLAGUE (BUBONIC)",
            "LEPROSY",
             "NOTIFIABLE DISEASES",
         
        ]
    },
    { 
        label: "MALARIA", 
        flag: "🦟",
        subtopics: [
            "GENERAL NOTES",
"MEDICINE PROPHYLAXIS", 
"TREATMENT OF MALARIA", 
"TREATMENT IN SPECIAL GROUPS", 
"TREATMENT FAILURE",
"SEVERE MALARIA",
"ARTESUNATE RECONSTITUTION",
"TREATMENT OF SEVERE MALARIA IN PREGNANCY",
"TREATMENT OF SEVERE MALARIA IN COMMUNITY", 
"TREATMENT OF MALARIA NI ELIMINATION AREAS",
        ]
    },
    { 
        label: "RESPIRATORY CONDITIONS", 
        flag: "🌬️",
        subtopics: [
            "ACUTE RESPIRATORY INFECTIONS NI ADULTS",
            "OUTPATIENT MANAGEMENT",
            "IN-PATIENT MANAGEMENT",
            "EMPYEMA",
            "HEALTHCARE ASSOCIATED INFECTIONS", 
            "CHRONIC OBSTRUCTIVE PULMONARY DISEASE", 
            "BRONCHIESTASIS",
            "ASTHMA",
            "ASTHMA IN CHILDREN",]
    },
    { 
        label: "CARDIOVASCULAR DISEASE", 
        flag: "❤️",
        subtopics: [ "MANAGEMENT OF HYPERTENSION",
 "MANAGEMENT OF SEVERE HYPERTENSION",
 "ACUTE MYOCARDIAL INFARCTION",
 "ARRYTHMIAS AFTER MYOCARDIAL INFARCTION", 
 "ENDORCARDITIS",
 "RHEUMATIC FEVER",
        ]
    },
    { 
        label: "GASTROINTESTINAL CONDITIONS", 
        flag: "🍽️",
        subtopics: [
            "ACID RELATED CONDITIONS",
"ACUTE DIARRHOEA AND ASSOCIATED CONDITIONS",
"BACILLARY DYSENTERY", 
"CHOLERA", 
"LIVER ABSCESS", 
"CHRONIC BOWEL DISORDERS",
"CONSTIPATION", 
"OTHER GASTROINTESTINAL PROBLEMS",
"LIVER DISEASE",
"BLEEDING OESOPHAGEAL VARICES", 
"ASCITES OF CHRONIC LIVER FAILURE", 
"CHRONIC HEPATITIS B & C",

        ]
    },
    { 
        label: "RENAL TRACT CONDITIONS", 
        flag: "💧",
        subtopics: [
            "URINARY TRACT INFECTIONS", 
"ACUTE KIDNEY INJURY",
"MANAGEMENT OF PRE-RENAL IMPAIRMENT",
"NEPHROTIC SYNDROME", 
"PRESCRIBING IN RENAL IMPAIRMENT/FAILURE", 
"END STAGE RENAL DISEASE", 
"CHRONIC DIALYSIS", ]

    },
    { 
        label: "RHEUMATOLOGICAL AND JOINT CONDITIONS", 
        flag: "🦴",
        subtopics: [
           "INFECTIONS",
"SEPTIC ARTHRITIS, AND ACUTE OSTEOMYELITIS",
"CHRONIC OSTEOMYELITIS",
"COMPOUND FRACTURES",
"BACK AND NECK PAIN",
"GOUT",
"RHEUMATOLOGICAL CONDITIONS",
"GENERAL GUIDELINES",
"SYSTEMIC CONNECTIVE TISSUE DISEASES",
"RHEUMATOID ARTHRITIS & JUVENILE CHRONIC ARTHRITIS",
"SYSTEMIC LUPUS ERYTHEMATOSUS (SLE)",
"DEGENERATIVE OSTEOARTHRITIS & SPINAL SPONDYLOSIS",
"RHEUMATOID FACTOR -VE SPONDYLOARTHROPATHIES",
"REITER’S DISEASE AND POST INFECTIVE ARTHRITIS",
        ]
    },
    { 
        label: "METABOLIC & ENDOCRINE CONDITIONS", 
        flag: "🧠",
        subtopics: [

            "DIABETES MELLITUS",	
"TYPES OF INSULIN",
"ORAL ANTI-DIABETIC AGENTS",
"DIABETIC DIET",
"SPECIAL PROBLEMS IN DIABETICS",
"SURGERY",	
"HYPERGLYCAEMIC COMA & PRE-COMA (ADULTS)",
"HYPERGLYCAEMIC COMA AND PRE-COMA (CHILDREN)",
"THYROID DISEASE",	
"GOITRE",
"HYPERTHYROIDISM",
"HYPOTHYROIDISM",
"HYPOADRENALISM",
            
        ]
    },
    { 
        label: "NEUROLOGICAL CONDITIONS", 
        flag: "🧠",
        subtopics: [
            "INFECTIONS OF THE NERVOUS SYSTEM",
"MENINGITIS",
"NEUROCYSTICERCOSIS",
"HEADACHE",
"TREATMENT OF PRIMARY HEADACHE",
"TENSION",
"MIGRAINE",
"COMBINATION",
"GENERAL NOTES",
"EPILEPSY",
"STATUS EPILEPTICUS",
"ACUTE CONFUSIONAL STATES",
"STROKE",
"PROGRESSIVE GENERALIZED WEAKNESS",
"PERIPHERAL SENSORY SYMPTOMS",
"INVOLUNTARY MOVEMENTS",
        ]
    },
    { 
        label: "MENTAL HEALTH", 
        flag: "🧠💭",
        subtopics: [
            "GENERAL GUIDELINES",
            "PRIORITY AREAS IN MENTAL HEALTH ",
            "PSYCHOSES",
            "ORGANIC PSYCHOSES",
            "MOOD (AFFECTIVE) DISORDERS",
            "HIV INDUCED MOOD DISORDERS DEPRESSION ", 
            "DEPRESSION	",
            "TREATMENT OF ALCOHOL DEPENDENCE	",
            "CHILD AND ADOLESCENT MENTAL HEALTH DISORDERS",
            
        ]
    },
    { 
        label: "COMMON EYE CONDITIONS", 
        flag: "👁️",
        subtopics: [
            "PREVENTION OF BLINDNESS",
"MANAGEMENT OF EYE CONDITIONS",
"DIAGNOSIS OF EYE CONDITIONS",
"ATRAUMATIC EYE CONDITIONS",
"XEROPHTHALMIA /VITAMIN A DEFICIENCY    ",
"CONJUNCTIVITIS OF THE NEWBORN",
"TRAUMATIC EYE CONDITIONS",
"PENETRATING INJURY",
"CORNEAL FOREIGN BODIES",
"CORNEAL ABRASION",
"CHEMICAL BURNS",
"IRITIS/ UVEITIS",
"CORNEAL ULCERS",
"GLAUCOMA (CHRONIC OPEN ANGLE)",
"CATARACT",
"EYE CONSUMABLES",
        ]
    },
    { 
        label: "COMMON ORAL CONDITIONS", 
        flag: "😁",
        subtopics: [
            "Oral problems",
"Management of Oral thrush/Oral candidiasis",
"Oesophageal Candidiasis",
"Herpes Simplex labialis",
"Kaposi’s Sarcoma",
"Gum infections",
"Dental Caries",
"Persistent Generalized Lymphadenopathy(PGL)",
"Oral Ulcers",
"Histoplasmosis",
        ]
    },
    { 
        label: "EAR NOSE AND THROAT DISORDERS", 
        flag: "👂👃👄",
        subtopics: [
            "Acute Otitis Media (AOM)",
"Recurrent Acute Otitis Media",	
"Acute Mastoiditis",	
"Otitis Media with Effusion",	
"For management REFER to Specialist",	
"Chronic suppurative otitis media",	
"Otitis Externa",	
"Malignant Otitis Externa",	
"Keratosis Obliterans",	
"RHINOLOGY",	
"Acute Rhinosinusitis",	
"Chronic Rhinosinusitis",	
"Allergic Rhinosinusitis",	
"Fungal Rhinosinusitis-Invasive",	
"Non-Invasive fungal Rhinosinusitis",	
"Obstructive sleep apnoea from adenotonsillar hypertrophy",	
"Tonsillitis-Acute",	
"Epistaxis",	
"CSF rhinorrhoea",	
"Croup",	
"Acute cervical lymphadenitis",	
           
        ]
    },
    { 
        label: "SKIN CONDITIONS", 
        flag: "🩹",
        subtopics: [
            "BACTERIAL INFECTIONS",
"IMPETIGO",
"FOLLICULITIS",
"FURUNCULOSIS",
"ERYSIPELAS",
"ACUTE CELLULITIS",
"PARONYCHIA",
"FUNGAL INFECTIONS",
"BODY RINGWORM (TINEA CORPORIS)",
"TINEA PEDIS (FUNGAL / ATHLETE'S FOOT)",
"PITYRIAS VERSICOLOR (TINEA VERSICOLOR)",
"SCALP RINGWORM (TINEA CAPITIS)",
"SCABIES",
"CUTANEOUS LARVA MIGRANS",
"VIRAL INFECTIONS",
"OTHER DERMATOLOGICAL CONDITIONS",
"ECZEMA",
"URTICARIA",
"PSORIASIS",
"PELLAGRA",
"ALBINISM/ VITILIGO",
"WARTS",

        ]
    },
    { 
        label: "BURNS", 
        flag: "🧯",
        subtopics: [
            "ASSESSMENT",
"GENERAL MANAGEMENT GUIDELINES",
"MANAGEMENT OF MODERATE BURNS",
"SMALL SURFACE AREA BURNS",
"LARGE SURFACE AREA BURNS",
"RESUSCITATION OF LARGE SURFACE AREA BURNS: ADULTS",
"RESUSCITATION OF LARGE SURFACE AREA BURNS:    CHILD",
"GENERAL NOTES",

        ]
    },
    { 
        label: "PAIN MANAGEMENT & CARE OF THE TERMINALLY ILL", 
        flag: "💊",
        subtopics: [
            "GENERAL NOTES",
            "PAIN MANAGEMENT",
            "MILD PAIN IN ADULTS",
            "MODERATE PAIN",
            "SEVERE PAIN",
            "ANTI-DEPRESSANTS AND NEUROLEPTICS",
            "MANAGEMENT OF PAIN IN CHILDREN",
            "CARE OF OTHER COMMON PALLIATIVE CARE SYMPTOMS IN CHILDREN AND ADULTS",
            "GIT",
            "CNS",
            "CARE OF THE TERMINALLY ILL",
        ]
    },
    { 
        label: "MEDICINES AND THE ELDERLY", 
        flag: "👴",
        subtopics: [
            "GENERAL NOTES",	
"ANTI-HYPERTENSIVES", 	
"DIURETICS", 	
"DIGOXIN", 	
"ORAL HYPOGLYCAEMICS", 	
"HYPNOTIC SEDATIVES", 	
"MAJOR TRANQUILLISERS",	
"ANTI- DIARRHOEALS",	
"NON-STEROIDAL ANTI-INFLAMMATORY MEDICINES", 	
"NARCOTICS", 	
"STEROIDS", 	

        ]
    },
    { 
        label: "HAEMATOLOGY AND BLOOD PRODUCTS", 
        flag: "🩸",
        subtopics: [
            "GENERAL NOTES",	
"ANAEMIA",	
"IRON DEFICIENCY ANAEMIA",	
"MEGALOBLASTIC ANAEMIA",	
"SICKLE CELL ANAEMIA",	
"G6PD DEFICIENCY",	
"OTHER ANAEMIAS",	
"HEREDITARY BLEEDING DISORDERS",	
"ACQUIRED BLEEDING DISORDERS/ PLATELET DISORDERS",	
"ANTICOAGULATION",	
"ORAL",	
"PROPHYLAXIS FOR DEEP VEIN THROMBOSIS (DVT)",	
"LIFE THREATENING PULMONARY EMBOLISM/ ARTERIAL EMBOLISM",	
"USE OF BLOOD AND BLOOD PRODUCTS",	
"USE OF BLOOD AND BLOOD PRODUCTS",	
"SPECIFIC INDICATIONS FOR USE OF BLOOD AND BLOOD PRODUCTS",	
"RED CELL CONCENTRATE (PACKED CELLS)",	
"PLATELET CONCENTRATES",	
"FRESH FROZEN PLASMA",	
"WHOLE BLOOD",	
"LEUKOCYTE-POOR BLOOD",	
"ANTI-D",	

        ]
    },
    { 
        label: "INTRAVENOUS FLUID REPLACEMENT", 
        flag: "💧",
        subtopics: [
            "NORMAL DAILY REQUIREMENTS",
"MAINTENANCE",
"REPLACEMENT OF ABNORMAL LOSSES",
"AVAILABLE INTRAVENOUS SOLUTIONS",
"CRYSTALLOIDS",
"COLLOIDS",

        ]
    },
    { 
        label: "ANAPHYLAXIS", 
        flag: "🐝",
        subtopics: [
            "General Notes",	
"Treatment",	
        ]
    },
    { 
        label: "POISONING", 
        flag: "☠️",
        subtopics: [
            "PREVENTION OF POISONING",
"GENERAL TREATMENT MEASURES",
"FIRST AID",
"SWALLOWED POISONS",
"CORROSIVE SUBSTANCES",
"INHALED POISONS",
"SKIN CONTAMINATION",
"EYE CONTAMINATION",
"TREATMENT OF SPECIFIC POISONINGS",
"ANTIDEPRESSANTS",
"ASPIRIN / SALICYLATE POISONING",
"CARBON MONOXIDE POISONING",
"CHLOROQUINE POISONING",
"PARACETAMOL POISONING",
"ETHANOL (ALCOHOL) POISONING",
"INSECTICIDES",
"ORGANOCHLORINE INSECTICIDES",
"PYRETHRUM AND SYNTHETIC PYRETHROIDS",
"ORGANOPHOSPHATE AND CARBAMATE INSECTICIDES",
"PARAQUAT AND RELATED HERBICIDES",
"PARAFFIN, PETROL AND OTHER PETROLEUM PRODUCTS",
"OTHER MEDICINES AND CHEMICALS",
"SNAKE BITE",
"SCORPION STING",
"MUSHROOMS",
        ]
    },
    { 
        label: "MEDICINES USED IN ANAESTHESIA", 
        flag: "💤",
        subtopics: [
            "GENERAL NOTES",
"GENERAL PRINCIPLES",
"GENERAL ANAESTHESIA",
"INTRAVENOUS ANAESTHETICS",
"THIOPENTONE SODIUM",
"ETOMIDATE",
"PROPOFOL",
"KETAMINE",
"INHALATIONAL ANAESTHETICS",
"NITROUS OXIDE",
"MEDICAL AIR",
"HALOTHANE",
"ISOFLURANE",
"SEVOFLURANE",
"MUSCLE RELAXANTS/ CHOLINESTERASE INHIBITORS",
"SUXAMETHONIUM CHLORIDE (DEPOLARISING)",
"ATRACURIUM BESYLATE (NON-DEPOLARISING)",
"ALCURONIUM CHLORIDE (NON-DEPOLARISING)",
"NEOSTIGMINE BROMIDE (CHOLINESTERASE INHIBITOR)",
"LOCAL ANAESTHESIA & CONDUCTION ANAESTHESIA",
"BUPIVACAINE HYDROCHLORIDE",
"BUPIVACAINE HYDROCHLORIDE (HEAVY)",
"LIGNOCAINE HYDROCHLORIDE",
"OTHER PERI-OPERATIVE MEDICINES",
"MEDICINES USED IN SHOCK",

        ]
    },
    { 
        label: "SURGICAL CONDITIONS", 
        flag: "🏥",
        subtopics: [
            "GENERAL NOTE",	
"GENERAL SURGICAL CONDITIONS",	
"ACUTE ABDOMEN",	
"ACUTE APPENDICITIS",	
"INTESTINAL OBSTRUCTION",	
"CHOLECYSTITIS",	
"TREATMENT OF ACUTE CHOLECYSTITIS",	
"PERFORATED DUODENAL ULCER",	
"BREAST CONDITIONS",	
"BREAST ABSCESS",	
"MASTITIS",	
"BREAST ECZEMA",	
"THYROID CONDITIONS",	
"SKIN ULCERS",
        ]
    },
    { 
        label: "SYSTEMIC THERAPY FOR CANCER", 
        flag: "🎗️",
        subtopics: [
            "GENERAL NOTES",	
"CHEMOTHERAPY",	
"OTHER SYSTEMIC THERAPIES",	
"PRINCIPLES OF COMBINATION CHEMOTHERAPY",	
"GUIDELINES FOR HANDLING CHEMOTHERAPY MEDICINES",	
"USE OF CHEMOTHERAPY",	
"ADJUVANT CHEMOTHERAPY",	
"NEOADJUVANT CHEMOTHERAPY",	
"CHEMORADIATION",	
"MAINTENANCE CHEMOTHERAPY",	
"PALLIATIVE CHEMOTHERAPY",	
"DOSE MODIFICATION",	
"SELECTION OF CHEMOTHERAPY AGENTS",	
"COMMON SIDE EFFECTS OF CHEMOTHERAPY",	
"FOLLOW UP",	

        ]
    },
    { 
        label: "REPORTING ADVERSE MEDICINE REACTIONS", 
        flag: "📋",
        subtopics: [
            "General Notes",
            
        ]
    }
];
